### ISSUE TITLE
Support for scatter plots

### ISSUE THREAD

**Issue by mattloose** [highslide-software/export-csv#62] opened 2015-07-30 17:18 UTC
I don't think this plugin correctly supports scatter plots - as with heat maps it appears to only output a subset of the data.

**Comment by highslide-software** [comment] 2015-08-06 13:10
Can you demonstrate that? Here's a scatter plot: http://jsfiddle.net/highcharts/cqjvD/894/

**Comment by personman** [comment] 2015-09-04 21:26
I'd like to try to improve it a bit. There are no labels in the current version. And if you have multiple series, the layout seems kind of strange. I made an attempt at a new version of the scatter and bubble exporter. Here's my pull request: #66

**Comment by highslide-software** [comment] 2015-09-25 07:28
Duplicate of #49 - two points with the same X values are not supported.

**Closed by highslide-software** 2015-09-25 07:28 UTC
